# Generated by Django 5.1.4 on 2025-01-02 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restrictions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrestriction",
            name="restriction_length",
        ),
    ]
