# Generated by Django 5.1.4 on 2025-01-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restrictions", "0002_remove_userrestriction_restriction_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrestriction",
            name="restriction_length",
            field=models.DurationField(
                blank=True,
                default=None,
                help_text="Specifies for how long this restriction applies. \nIf unspecified - user is restricted permanently",
                null=True,
            ),
        ),
    ]
