# Generated by Django 5.1.4 on 2025-01-04 21:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("platform", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restriction_type", models.IntegerField(choices=[(0, "Ban")])),
                (
                    "restriction_reason",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "restricted_since",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "restriction_length",
                    models.DurationField(
                        blank=True,
                        default=None,
                        help_text="Specifies for how long this restriction applies. \nIf unspecified - user is restricted permanently",
                        null=True,
                    ),
                ),
                (
                    "platform_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restrictions",
                        to="platform.platformuser",
                    ),
                ),
            ],
        ),
    ]
