# Generated by Django 5.1.4 on 2025-01-05 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0001_initial"),
        ("restrictions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrestriction",
            name="platform_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restrictions",
                to="platform.platformgroup",
            ),
        ),
    ]
