# Generated by Django 5.1.4 on 2025-01-07 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0001_initial"),
        ("restrictions", "0002_userrestriction_platform_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrestriction",
            name="restricted_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="User who casted this restriction upon the platform_user.\nIf unspecified - then its either a netban or initiator has deleted their account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_restrictions",
                to="platform.platformuser",
            ),
        ),
    ]
